version: "3.9"

services:
  app:
    # build context tell that we want to build our docker file in current directory
    build:
      context: .
      # args specifies that we are runing app using docker-compose which we are using only for development we will set build args "DEV" to true
      args:
        - DEV=true
    ports:
      - 8000:8000
    # volumes are a way of mapping directroies from our system into the docker conatiner
    # we do this so that in real time changes from our local system can be reflatect on conatiner and avoid rebuilding the conatiner
    volumes:
      - ./app:/app
    # below command is default command to run the service and we can change the command from cli
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
